name: CI-MLflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'

      - name: Check environment
        run: python --version

      - name: Install dependencies
        run: pip install mlflow==2.19.0 scikit-learn pandas numpy

      - name: Run MLflow project
        run: mlflow run MLProject

      - name: Get latest MLflow run_id
        run: echo "Run completed successfully"